// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metadata

import (
	"image"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlurHashAPI creates a new instance of MockBlurHashAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlurHashAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlurHashAPI {
	mock := &MockBlurHashAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlurHashAPI is an autogenerated mock type for the BlurHashAPI type
type MockBlurHashAPI struct {
	mock.Mock
}

type MockBlurHashAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlurHashAPI) EXPECT() *MockBlurHashAPI_Expecter {
	return &MockBlurHashAPI_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockBlurHashAPI
func (_mock *MockBlurHashAPI) Decode(hash string, width int, height int, punch int) (image.Image, error) {
	ret := _mock.Called(hash, width, height, punch)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 image.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int, int) (image.Image, error)); ok {
		return returnFunc(hash, width, height, punch)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int, int) image.Image); ok {
		r0 = returnFunc(hash, width, height, punch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int, int) error); ok {
		r1 = returnFunc(hash, width, height, punch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlurHashAPI_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockBlurHashAPI_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - hash string
//   - width int
//   - height int
//   - punch int
func (_e *MockBlurHashAPI_Expecter) Decode(hash interface{}, width interface{}, height interface{}, punch interface{}) *MockBlurHashAPI_Decode_Call {
	return &MockBlurHashAPI_Decode_Call{Call: _e.mock.On("Decode", hash, width, height, punch)}
}

func (_c *MockBlurHashAPI_Decode_Call) Run(run func(hash string, width int, height int, punch int)) *MockBlurHashAPI_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlurHashAPI_Decode_Call) Return(image1 image.Image, err error) *MockBlurHashAPI_Decode_Call {
	_c.Call.Return(image1, err)
	return _c
}

func (_c *MockBlurHashAPI_Decode_Call) RunAndReturn(run func(hash string, width int, height int, punch int) (image.Image, error)) *MockBlurHashAPI_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockBlurHashAPI
func (_mock *MockBlurHashAPI) Encode(xComponents int, yComponents int, rgba image.Image) (string, error) {
	ret := _mock.Called(xComponents, yComponents, rgba)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int, image.Image) (string, error)); ok {
		return returnFunc(xComponents, yComponents, rgba)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, image.Image) string); ok {
		r0 = returnFunc(xComponents, yComponents, rgba)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, image.Image) error); ok {
		r1 = returnFunc(xComponents, yComponents, rgba)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlurHashAPI_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockBlurHashAPI_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - xComponents int
//   - yComponents int
//   - rgba image.Image
func (_e *MockBlurHashAPI_Expecter) Encode(xComponents interface{}, yComponents interface{}, rgba interface{}) *MockBlurHashAPI_Encode_Call {
	return &MockBlurHashAPI_Encode_Call{Call: _e.mock.On("Encode", xComponents, yComponents, rgba)}
}

func (_c *MockBlurHashAPI_Encode_Call) Run(run func(xComponents int, yComponents int, rgba image.Image)) *MockBlurHashAPI_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 image.Image
		if args[2] != nil {
			arg2 = args[2].(image.Image)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlurHashAPI_Encode_Call) Return(s string, err error) *MockBlurHashAPI_Encode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBlurHashAPI_Encode_Call) RunAndReturn(run func(xComponents int, yComponents int, rgba image.Image) (string, error)) *MockBlurHashAPI_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// IsValid provides a mock function for the type MockBlurHashAPI
func (_mock *MockBlurHashAPI) IsValid(hash string) bool {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBlurHashAPI_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type MockBlurHashAPI_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - hash string
func (_e *MockBlurHashAPI_Expecter) IsValid(hash interface{}) *MockBlurHashAPI_IsValid_Call {
	return &MockBlurHashAPI_IsValid_Call{Call: _e.mock.On("IsValid", hash)}
}

func (_c *MockBlurHashAPI_IsValid_Call) Run(run func(hash string)) *MockBlurHashAPI_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlurHashAPI_IsValid_Call) Return(b bool) *MockBlurHashAPI_IsValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBlurHashAPI_IsValid_Call) RunAndReturn(run func(hash string) bool) *MockBlurHashAPI_IsValid_Call {
	_c.Call.Return(run)
	return _c
}
