// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"github.com/fingertips18/fingertips18.github.io/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailRepository creates a new instance of MockEmailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailRepository {
	mock := &MockEmailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailRepository is an autogenerated mock type for the EmailRepository type
type MockEmailRepository struct {
	mock.Mock
}

type MockEmailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailRepository) EXPECT() *MockEmailRepository_Expecter {
	return &MockEmailRepository_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockEmailRepository
func (_mock *MockEmailRepository) Send(send domain.SendEmail) error {
	ret := _mock.Called(send)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.SendEmail) error); ok {
		r0 = returnFunc(send)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailRepository_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailRepository_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - send domain.SendEmail
func (_e *MockEmailRepository_Expecter) Send(send interface{}) *MockEmailRepository_Send_Call {
	return &MockEmailRepository_Send_Call{Call: _e.mock.On("Send", send)}
}

func (_c *MockEmailRepository_Send_Call) Run(run func(send domain.SendEmail)) *MockEmailRepository_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.SendEmail
		if args[0] != nil {
			arg0 = args[0].(domain.SendEmail)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailRepository_Send_Call) Return(err error) *MockEmailRepository_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailRepository_Send_Call) RunAndReturn(run func(send domain.SendEmail) error) *MockEmailRepository_Send_Call {
	_c.Call.Return(run)
	return _c
}
