// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fingertips18/fingertips18.github.io/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillRepository creates a new instance of MockSkillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepository {
	mock := &MockSkillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepository is an autogenerated mock type for the SkillRepository type
type MockSkillRepository struct {
	mock.Mock
}

type MockSkillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepository) EXPECT() *MockSkillRepository_Expecter {
	return &MockSkillRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSkillRepository
func (_mock *MockSkillRepository) Create(ctx context.Context, skill *domain.CreateSkill) (string, error) {
	ret := _mock.Called(ctx, skill)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateSkill) (string, error)); ok {
		return returnFunc(ctx, skill)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateSkill) string); ok {
		r0 = returnFunc(ctx, skill)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateSkill) error); ok {
		r1 = returnFunc(ctx, skill)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSkillRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - skill *domain.CreateSkill
func (_e *MockSkillRepository_Expecter) Create(ctx interface{}, skill interface{}) *MockSkillRepository_Create_Call {
	return &MockSkillRepository_Create_Call{Call: _e.mock.On("Create", ctx, skill)}
}

func (_c *MockSkillRepository_Create_Call) Run(run func(ctx context.Context, skill *domain.CreateSkill)) *MockSkillRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateSkill
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateSkill)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepository_Create_Call) Return(s string, err error) *MockSkillRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSkillRepository_Create_Call) RunAndReturn(run func(ctx context.Context, skill *domain.CreateSkill) (string, error)) *MockSkillRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
