// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPGXAPI creates a new instance of MockPGXAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPGXAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPGXAPI {
	mock := &MockPGXAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPGXAPI is an autogenerated mock type for the PGXAPI type
type MockPGXAPI struct {
	mock.Mock
}

type MockPGXAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPGXAPI) EXPECT() *MockPGXAPI_Expecter {
	return &MockPGXAPI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPGXAPI
func (_mock *MockPGXAPI) Close() {
	_mock.Called()
	return
}

// MockPGXAPI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPGXAPI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPGXAPI_Expecter) Close() *MockPGXAPI_Close_Call {
	return &MockPGXAPI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPGXAPI_Close_Call) Run(run func()) *MockPGXAPI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPGXAPI_Close_Call) Return() *MockPGXAPI_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPGXAPI_Close_Call) RunAndReturn(run func()) *MockPGXAPI_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function for the type MockPGXAPI
func (_mock *MockPGXAPI) Exec(ctx context.Context, query string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPGXAPI_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockPGXAPI_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockPGXAPI_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *MockPGXAPI_Exec_Call {
	return &MockPGXAPI_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockPGXAPI_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockPGXAPI_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPGXAPI_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockPGXAPI_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockPGXAPI_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (pgconn.CommandTag, error)) *MockPGXAPI_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockPGXAPI
func (_mock *MockPGXAPI) Query(ctx context.Context, query string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPGXAPI_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPGXAPI_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockPGXAPI_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *MockPGXAPI_Query_Call {
	return &MockPGXAPI_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockPGXAPI_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockPGXAPI_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPGXAPI_Query_Call) Return(rows pgx.Rows, err error) *MockPGXAPI_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockPGXAPI_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (pgx.Rows, error)) *MockPGXAPI_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockPGXAPI
func (_mock *MockPGXAPI) QueryRow(ctx context.Context, query string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockPGXAPI_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockPGXAPI_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockPGXAPI_Expecter) QueryRow(ctx interface{}, query interface{}, args ...interface{}) *MockPGXAPI_QueryRow_Call {
	return &MockPGXAPI_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockPGXAPI_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockPGXAPI_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPGXAPI_QueryRow_Call) Return(row pgx.Row) *MockPGXAPI_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockPGXAPI_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) pgx.Row) *MockPGXAPI_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
