// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsHandler creates a new instance of MockAnalyticsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsHandler {
	mock := &MockAnalyticsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsHandler is an autogenerated mock type for the AnalyticsHandler type
type MockAnalyticsHandler struct {
	mock.Mock
}

type MockAnalyticsHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsHandler) EXPECT() *MockAnalyticsHandler_Expecter {
	return &MockAnalyticsHandler_Expecter{mock: &_m.Mock}
}

// PageView provides a mock function for the type MockAnalyticsHandler
func (_mock *MockAnalyticsHandler) PageView(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockAnalyticsHandler_PageView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageView'
type MockAnalyticsHandler_PageView_Call struct {
	*mock.Call
}

// PageView is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockAnalyticsHandler_Expecter) PageView(w interface{}, r interface{}) *MockAnalyticsHandler_PageView_Call {
	return &MockAnalyticsHandler_PageView_Call{Call: _e.mock.On("PageView", w, r)}
}

func (_c *MockAnalyticsHandler_PageView_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockAnalyticsHandler_PageView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsHandler_PageView_Call) Return() *MockAnalyticsHandler_PageView_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsHandler_PageView_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockAnalyticsHandler_PageView_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockAnalyticsHandler
func (_mock *MockAnalyticsHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockAnalyticsHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockAnalyticsHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockAnalyticsHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockAnalyticsHandler_ServeHTTP_Call {
	return &MockAnalyticsHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockAnalyticsHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockAnalyticsHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsHandler_ServeHTTP_Call) Return() *MockAnalyticsHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockAnalyticsHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
