// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailHandler creates a new instance of MockEmailHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailHandler {
	mock := &MockEmailHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailHandler is an autogenerated mock type for the EmailHandler type
type MockEmailHandler struct {
	mock.Mock
}

type MockEmailHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailHandler) EXPECT() *MockEmailHandler_Expecter {
	return &MockEmailHandler_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockEmailHandler
func (_mock *MockEmailHandler) Send(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockEmailHandler_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailHandler_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockEmailHandler_Expecter) Send(w interface{}, r interface{}) *MockEmailHandler_Send_Call {
	return &MockEmailHandler_Send_Call{Call: _e.mock.On("Send", w, r)}
}

func (_c *MockEmailHandler_Send_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockEmailHandler_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailHandler_Send_Call) Return() *MockEmailHandler_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEmailHandler_Send_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockEmailHandler_Send_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockEmailHandler
func (_mock *MockEmailHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockEmailHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockEmailHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockEmailHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockEmailHandler_ServeHTTP_Call {
	return &MockEmailHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockEmailHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockEmailHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailHandler_ServeHTTP_Call) Return() *MockEmailHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEmailHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockEmailHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
