// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileHandler creates a new instance of MockFileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileHandler {
	mock := &MockFileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileHandler is an autogenerated mock type for the FileHandler type
type MockFileHandler struct {
	mock.Mock
}

type MockFileHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileHandler) EXPECT() *MockFileHandler_Expecter {
	return &MockFileHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) Create(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockFileHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockFileHandler_Expecter) Create(w interface{}, r interface{}) *MockFileHandler_Create_Call {
	return &MockFileHandler_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *MockFileHandler_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_Create_Call) Return() *MockFileHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_Create_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) Delete(w http.ResponseWriter, r *http.Request, id string) {
	_mock.Called(w, r, id)
	return
}

// MockFileHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - id string
func (_e *MockFileHandler_Expecter) Delete(w interface{}, r interface{}, id interface{}) *MockFileHandler_Delete_Call {
	return &MockFileHandler_Delete_Call{Call: _e.mock.On("Delete", w, r, id)}
}

func (_c *MockFileHandler_Delete_Call) Run(run func(w http.ResponseWriter, r *http.Request, id string)) *MockFileHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileHandler_Delete_Call) Return() *MockFileHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_Delete_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, id string)) *MockFileHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// DeleteByParent provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) DeleteByParent(w http.ResponseWriter, r *http.Request, parentTable string, parentID string) {
	_mock.Called(w, r, parentTable, parentID)
	return
}

// MockFileHandler_DeleteByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByParent'
type MockFileHandler_DeleteByParent_Call struct {
	*mock.Call
}

// DeleteByParent is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - parentTable string
//   - parentID string
func (_e *MockFileHandler_Expecter) DeleteByParent(w interface{}, r interface{}, parentTable interface{}, parentID interface{}) *MockFileHandler_DeleteByParent_Call {
	return &MockFileHandler_DeleteByParent_Call{Call: _e.mock.On("DeleteByParent", w, r, parentTable, parentID)}
}

func (_c *MockFileHandler_DeleteByParent_Call) Run(run func(w http.ResponseWriter, r *http.Request, parentTable string, parentID string)) *MockFileHandler_DeleteByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileHandler_DeleteByParent_Call) Return() *MockFileHandler_DeleteByParent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_DeleteByParent_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, parentTable string, parentID string)) *MockFileHandler_DeleteByParent_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) Get(w http.ResponseWriter, r *http.Request, id string) {
	_mock.Called(w, r, id)
	return
}

// MockFileHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFileHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - id string
func (_e *MockFileHandler_Expecter) Get(w interface{}, r interface{}, id interface{}) *MockFileHandler_Get_Call {
	return &MockFileHandler_Get_Call{Call: _e.mock.On("Get", w, r, id)}
}

func (_c *MockFileHandler_Get_Call) Run(run func(w http.ResponseWriter, r *http.Request, id string)) *MockFileHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileHandler_Get_Call) Return() *MockFileHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_Get_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, id string)) *MockFileHandler_Get_Call {
	_c.Run(run)
	return _c
}

// ListByParent provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) ListByParent(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockFileHandler_ListByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByParent'
type MockFileHandler_ListByParent_Call struct {
	*mock.Call
}

// ListByParent is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockFileHandler_Expecter) ListByParent(w interface{}, r interface{}) *MockFileHandler_ListByParent_Call {
	return &MockFileHandler_ListByParent_Call{Call: _e.mock.On("ListByParent", w, r)}
}

func (_c *MockFileHandler_ListByParent_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_ListByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_ListByParent_Call) Return() *MockFileHandler_ListByParent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_ListByParent_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_ListByParent_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockFileHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockFileHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockFileHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockFileHandler_ServeHTTP_Call {
	return &MockFileHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockFileHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockFileHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_ServeHTTP_Call) Return() *MockFileHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockFileHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MockFileHandler
func (_mock *MockFileHandler) Update(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockFileHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFileHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockFileHandler_Expecter) Update(w interface{}, r interface{}) *MockFileHandler_Update_Call {
	return &MockFileHandler_Update_Call{Call: _e.mock.On("Update", w, r)}
}

func (_c *MockFileHandler_Update_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileHandler_Update_Call) Return() *MockFileHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileHandler_Update_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockFileHandler_Update_Call {
	_c.Run(run)
	return _c
}
