// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageHandler creates a new instance of MockImageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageHandler {
	mock := &MockImageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageHandler is an autogenerated mock type for the ImageHandler type
type MockImageHandler struct {
	mock.Mock
}

type MockImageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageHandler) EXPECT() *MockImageHandler_Expecter {
	return &MockImageHandler_Expecter{mock: &_m.Mock}
}

// ServeHTTP provides a mock function for the type MockImageHandler
func (_mock *MockImageHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockImageHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockImageHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockImageHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockImageHandler_ServeHTTP_Call {
	return &MockImageHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockImageHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockImageHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageHandler_ServeHTTP_Call) Return() *MockImageHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockImageHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockImageHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// Upload provides a mock function for the type MockImageHandler
func (_mock *MockImageHandler) Upload(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockImageHandler_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageHandler_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockImageHandler_Expecter) Upload(w interface{}, r interface{}) *MockImageHandler_Upload_Call {
	return &MockImageHandler_Upload_Call{Call: _e.mock.On("Upload", w, r)}
}

func (_c *MockImageHandler_Upload_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockImageHandler_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageHandler_Upload_Call) Return() *MockImageHandler_Upload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockImageHandler_Upload_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockImageHandler_Upload_Call {
	_c.Run(run)
	return _c
}
