import {
  AQUILARIE,
  CONVOCADE,
  //FINGERTIPS,
  GOTWORKDIGITAL,
  GRADUATESCHOOL,
  MYCAA,
} from './assets';

export const EXPERIENCES = [
  // {
  //   image: FINGERTIPS,
  //   position: "Freelance Software Developer",
  //   company: "Fingertips",
  //   link: "https://fingertips18.github.io",
  //   setup: "Remote",
  //   date: "July 2022 – June 2024",
  //   highlights: [
  //     "Developed and deployed 5+ custom mobile applications for Android using Flutter and 5+ web applications using React Frameworks, enhancing user engagement and client satisfaction.",
  //     "Designed and implemented responsive web applications with HTML, CSS and Javascript with React framework for local clients.",
  //     "Integrated third-party APIs (oauth, mapping services, etc.) and conducted thorough testing, ensuring high performance and security.",
  //     "Collaborated with clients to gather requirements, deliver projects within the timelines and budgets, and provided ongoing maintenance, resulting in 95% client retention.",
  //   ],
  //   skills: [
  //     "Android Development",
  //     "Web Development",
  //     "Web Design",
  //     "Frontend Development",
  //     "Backed Development",
  //     "React JS",
  //     "Next JS",
  //     "Express JS",
  //     "MongoDB",
  //     "Clerk",
  //     "Vercel",
  //     "Netlify",
  //     "Github Pages",
  //     "Tailwind CSS",
  //     "Figma",
  //     "Photoshop",
  //     "MVC",
  //     "REST API",
  //     "Rive",
  //     "Unity",
  //     "Tensorflow",
  //     "Tflite",
  //   ],
  // },
  {
    image: GOTWORKDIGITAL,
    position: 'Mobile Application Developer',
    company: 'GotWork Digital',
    link: 'https://gotwork.digital',
    setup: 'Remote',
    date: 'May 2023 – April 2024',
    highlights: [
      'Transitioned MindFree application to Flutter from its previous tech stack, implementing 8 intricate user interface designs from Figma, resulting in a 20% boost in user satisfaction.',
      'Developed applications using Feature First Clean Architecture, leveraging Riverpod and Bloc for robust state management, adhering to industry best practices.',
      'Enhanced app functionality through regular software updates and integration of new dependencies, consistently delivering new features and improvements.',
      'Actively collaborated with a senior software engineer, gaining valuable mentorship, and contributed to team success by sharing updates and insights in weekly meetings.',
    ],
    skills: [
      'Flutter',
      'Firebase',
      'Cloud Firestore',
      'Supabase',
      'Trello',
      'Bloc',
      'Riverpod',
      'GoRouter',
      'GetIt',
      'Figma',
      'Bitbucket',
      'Unit Testing',
      'Clean Architecture',
      'MVVM',
      'REST API',
    ],
  },
  {
    image: CONVOCADE,
    position: 'Software Developer',
    company: 'Convocade',
    link: 'https://www.facebook.com/Convocade',
    setup: 'Remote',
    date: 'July 2022 – January 2023',
    highlights: [
      'Developed a web app using ReactJS and was migrated to NextJS for advance features, enabling businesses to hire influencers for advertisement, connecting over 3+ businesses with influencers.',
      'Implemented dynamic features like monthly influencer rotation and influencer of the week, enhancing user engagement and platform activity by 35%.',
      'Created a seamless booking system for influencers and businesses, prioritizing popular influencers while providing flexibility for lesser- known influencers to gain exposure, optimizing the hiring process for all parties involved.',
      'Developed a dynamic landing page to assist 100+ eligible military spouses in obtaining professional credentials, facilitating their career advancement.',
      'Developed a music player web app to showcase over 3+ tracks produced by Aquilarie, enhancing their online presence and audience reach.',
    ],
    subCompanies: [
      {
        company: 'MyCAA Grant Assist',
        image: MYCAA,
        link: 'https://mycaagrant.com',
      },
      {
        company: 'Aquilarie',
        image: AQUILARIE,
        link: 'https://spotify.com/artist/2F2fMy2GAqcw2k7fk97kSk',
      },
    ],
    skills: [
      'React JS',
      'Next JS',
      'Tailwind CSS',
      'Redux JS',
      'Zustand',
      'Express JS',
      'Uploadthing',
      'Clerk',
      'Framer Motion',
      'GSAP',
      'Figma',
      'Zod',
      'React Hook Form',
      'Shadcn UI',
    ],
  },
  {
    image: GRADUATESCHOOL,
    position: 'Full-Stack Developer Intern',
    company: 'USM Graduate School',
    link: 'https://www.usm.edu.ph/academics/graduate-school',
    setup: 'On-site',
    date: 'January 2021 – June 2021',
    highlights: [
      'Led the development of the Mastivity Web Application for USM Graduate School Faculty, managing both Frontend and Backend, resulting in a 20% increase in user engagement.',
      "Conducted regular software updates and delivered comprehensive presentations of the web application, ensuring stakeholders were updated and satisfied with the system's progress.",
      'Maintained an active presence, dedicating 8 hours in-office daily and continued work remotely, contributing to 95% uptime and reliability of the system.',
      'Enhanced skill set by mastering ASP.NET Core and Angular framework, resulting in a 30% improvement in development efficiency and project completion time.',
    ],
    skills: [
      'ASP.Net Core',
      'Angular',
      'Angular Material',
      'Azure',
      'MSSQL Server',
      'Swagger API',
      'Entity Framework (EF) Core',
      'Bootstrap',
      'SCSS',
      'HTML',
      'JSON Web Token (JWT)',
    ],
  },
];
