import {
  SiAdobephotoshop,
  SiAdobephotoshopHex,
  SiAndroidstudio,
  SiAndroidstudioHex,
  SiBitbucket,
  SiBitbucketHex,
  SiBootstrap,
  SiBootstrapHex,
  SiClerk,
  SiClerkHex,
  SiCss3,
  SiCss3Hex,
  SiDart,
  SiDartHex,
  SiDocker,
  SiDockerHex,
  SiDotnet,
  SiDotnetHex,
  SiExpress,
  SiExpressHex,
  SiFigma,
  SiFigmaHex,
  SiFirebase,
  SiFirebaseHex,
  SiFlutter,
  SiFlutterHex,
  SiGit,
  SiGitHex,
  SiGithub,
  SiGithubHex,
  SiGithubpages,
  SiGithubpagesHex,
  SiGo,
  SiGoHex,
  SiGooglecolab,
  SiGooglecolabHex,
  SiHtml5,
  SiHtml5Hex,
  SiJavascript,
  SiJavascriptHex,
  SiJupyter,
  SiJupyterHex,
  SiLaravel,
  SiLaravelHex,
  SiMongodb,
  SiMongodbHex,
  SiMysql,
  SiMysqlHex,
  SiNetlify,
  SiNetlifyHex,
  SiNextdotjs,
  SiNextdotjsHex,
  SiNodedotjs,
  SiNodedotjsHex,
  SiNotion,
  SiNotionHex,
  SiPostgresql,
  SiPostgresqlHex,
  SiPostman,
  SiPostmanHex,
  SiPrisma,
  SiPrismaHex,
  SiPython,
  SiPythonHex,
  SiRailway,
  SiRailwayHex,
  SiReact,
  SiReactHex,
  SiReacthookform,
  SiReacthookformHex,
  SiRedux,
  SiReduxHex,
  SiRender,
  SiRenrenHex,
  SiRive,
  SiRiveHex,
  SiSentry,
  SiSentryHex,
  SiShadcnui,
  SiShadcnuiHex,
  SiSupabase,
  SiSupabaseHex,
  SiSwagger,
  SiSwaggerHex,
  SiTailwindcss,
  SiTailwindcssHex,
  SiTensorflow,
  SiTensorflowHex,
  SiTrello,
  SiTrelloHex,
  SiTypeformHex,
  SiTypescript,
  SiUnity,
  SiUnityHex,
  SiVercel,
  SiVercelHex,
  SiVite,
  SiViteHex,
  SiZod,
  SiZodHex,
} from "@icons-pack/react-simple-icons";

export const FRONTEND = [
  {
    icon: SiHtml5,
    hexColor: SiHtml5Hex,
    label: "HTML",
  },
  {
    icon: SiCss3,
    hexColor: SiCss3Hex,
    label: "CSS",
  },
  {
    icon: SiJavascript,
    hexColor: SiJavascriptHex,
    label: "Javascript",
  },
  {
    icon: SiTypescript,
    hexColor: SiTypeformHex,
    label: "Typescript",
  },
  {
    icon: SiDart,
    hexColor: SiDartHex,
    label: "Dart",
  },
  {
    icon: SiReact,
    hexColor: SiReactHex,
    label: "React JS",
  },
  {
    icon: SiNextdotjs,
    hexColor: SiNextdotjsHex,
    label: "Next JS",
  },
  {
    icon: SiFlutter,
    hexColor: SiFlutterHex,
    label: "Flutter",
  },
  {
    icon: SiShadcnui,
    hexColor: SiShadcnuiHex,
    label: "Shadcnui",
  },
  {
    icon: SiTailwindcss,
    hexColor: SiTailwindcssHex,
    label: "TailwindCSS",
  },
  {
    icon: SiBootstrap,
    hexColor: SiBootstrapHex,
    label: "Bootstrap",
  },
  {
    icon: SiRedux,
    hexColor: SiReduxHex,
    label: "Redux",
  },
  {
    icon: SiZod,
    hexColor: SiZodHex,
    label: "Zod",
  },
  {
    icon: SiReacthookform,
    hexColor: SiReacthookformHex,
    label: "React Hook Form",
  },
  {
    icon: SiClerk,
    hexColor: SiClerkHex,
    label: "Clerk",
  },
  {
    icon: SiVite,
    hexColor: SiViteHex,
    label: "Vite",
  },
];

export const BACKEND = [
  {
    icon: SiNodedotjs,
    hexColor: SiNodedotjsHex,
    label: "Node JS",
  },
  {
    icon: SiExpress,
    hexColor: SiExpressHex,
    label: "Express JS",
  },
  {
    icon: SiGo,
    hexColor: SiGoHex,
    label: "Go",
  },
  {
    icon: SiLaravel,
    hexColor: SiLaravelHex,
    label: "Laravel",
  },
  {
    icon: SiDotnet,
    hexColor: SiDotnetHex,
    label: ".NET",
  },
  {
    icon: SiMongodb,
    hexColor: SiMongodbHex,
    label: "MongoDB",
  },
  {
    icon: SiSupabase,
    hexColor: SiSupabaseHex,
    label: "Supabase",
  },
  {
    icon: SiFirebase,
    hexColor: SiFirebaseHex,
    label: "Firebase",
  },
  {
    icon: SiPrisma,
    hexColor: SiPrismaHex,
    label: "Prisma ORM",
  },
  {
    icon: SiMysql,
    hexColor: SiMysqlHex,
    label: "MySQL",
  },
  {
    icon: SiPostgresql,
    hexColor: SiPostgresqlHex,
    label: "PostgreSQL",
  },
  {
    icon: SiSwagger,
    hexColor: SiSwaggerHex,
    label: "Swagger",
  },
];

export const OTHERS = [
  {
    icon: SiGit,
    hexColor: SiGitHex,
    label: "Git",
  },
  {
    icon: SiGithub,
    hexColor: SiGithubHex,
    label: "GitHub",
  },
  {
    icon: SiBitbucket,
    hexColor: SiBitbucketHex,
    label: "Bitbucket",
  },
  {
    icon: SiVercel,
    hexColor: SiVercelHex,
    label: "Vercel",
  },
  {
    icon: SiNetlify,
    hexColor: SiNetlifyHex,
    label: "Netlify",
  },
  {
    icon: SiRender,
    hexColor: SiRenrenHex,
    label: "Render",
  },
  {
    icon: SiRailway,
    hexColor: SiRailwayHex,
    label: "Railway",
  },
  {
    icon: SiGithubpages,
    hexColor: SiGithubpagesHex,
    label: "Github Pages",
  },
  {
    icon: SiPython,
    hexColor: SiPythonHex,
    label: "Python",
  },
  {
    icon: SiTensorflow,
    hexColor: SiTensorflowHex,
    label: "Tensorflow",
  },
  {
    icon: SiUnity,
    hexColor: SiUnityHex,
    label: "Unity",
  },
  {
    icon: SiAndroidstudio,
    hexColor: SiAndroidstudioHex,
    label: "Android Studio",
  },
];

export const TOOLS = [
  {
    icon: SiDocker,
    hexColor: SiDockerHex,
    label: "Docker",
  },
  {
    icon: SiGooglecolab,
    hexColor: SiGooglecolabHex,
    label: "Google Colab",
  },
  {
    icon: SiJupyter,
    hexColor: SiJupyterHex,
    label: "Jupyter",
  },
  {
    icon: SiFigma,
    hexColor: SiFigmaHex,
    label: "Figma",
  },
  {
    icon: SiRive,
    hexColor: SiRiveHex,
    label: "Rive",
  },
  {
    icon: SiAdobephotoshop,
    hexColor: SiAdobephotoshopHex,
    label: "Adobo Photoshop",
  },
  {
    icon: SiTrello,
    hexColor: SiTrelloHex,
    label: "Trello",
  },
  {
    icon: SiNotion,
    hexColor: SiNotionHex,
    label: "Notion",
  },
  {
    icon: SiPostman,
    hexColor: SiPostmanHex,
    label: "Postman",
  },
  {
    icon: SiSentry,
    hexColor: SiSentryHex,
    label: "Sentry",
  },
];
