// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillHandler creates a new instance of MockSkillHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillHandler {
	mock := &MockSkillHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillHandler is an autogenerated mock type for the SkillHandler type
type MockSkillHandler struct {
	mock.Mock
}

type MockSkillHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillHandler) EXPECT() *MockSkillHandler_Expecter {
	return &MockSkillHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSkillHandler
func (_mock *MockSkillHandler) Create(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSkillHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSkillHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSkillHandler_Expecter) Create(w interface{}, r interface{}) *MockSkillHandler_Create_Call {
	return &MockSkillHandler_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *MockSkillHandler_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSkillHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillHandler_Create_Call) Return() *MockSkillHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkillHandler_Create_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSkillHandler_Create_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockSkillHandler
func (_mock *MockSkillHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockSkillHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockSkillHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockSkillHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *MockSkillHandler_ServeHTTP_Call {
	return &MockSkillHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *MockSkillHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockSkillHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillHandler_ServeHTTP_Call) Return() *MockSkillHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSkillHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockSkillHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
