// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fingertips18/fingertips18.github.io/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Create(ctx context.Context, file domain.File) (string, error) {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) (string, error)); ok {
		return returnFunc(ctx, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) string); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.File) error); ok {
		r1 = returnFunc(ctx, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - file domain.File
func (_e *MockFileRepository_Expecter) Create(ctx interface{}, file interface{}) *MockFileRepository_Create_Call {
	return &MockFileRepository_Create_Call{Call: _e.mock.On("Create", ctx, file)}
}

func (_c *MockFileRepository_Create_Call) Run(run func(ctx context.Context, file domain.File)) *MockFileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.File
		if args[1] != nil {
			arg1 = args[1].(domain.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Create_Call) Return(s string, err error) *MockFileRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileRepository_Create_Call) RunAndReturn(run func(ctx context.Context, file domain.File) (string, error)) *MockFileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFileRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockFileRepository_Delete_Call {
	return &MockFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFileRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Delete_Call) Return(err error) *MockFileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByParent provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) DeleteByParent(ctx context.Context, parentTable string, parentID string) error {
	ret := _mock.Called(ctx, parentTable, parentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByParent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, parentTable, parentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_DeleteByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByParent'
type MockFileRepository_DeleteByParent_Call struct {
	*mock.Call
}

// DeleteByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - parentTable string
//   - parentID string
func (_e *MockFileRepository_Expecter) DeleteByParent(ctx interface{}, parentTable interface{}, parentID interface{}) *MockFileRepository_DeleteByParent_Call {
	return &MockFileRepository_DeleteByParent_Call{Call: _e.mock.On("DeleteByParent", ctx, parentTable, parentID)}
}

func (_c *MockFileRepository_DeleteByParent_Call) Run(run func(ctx context.Context, parentTable string, parentID string)) *MockFileRepository_DeleteByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_DeleteByParent_Call) Return(err error) *MockFileRepository_DeleteByParent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_DeleteByParent_Call) RunAndReturn(run func(ctx context.Context, parentTable string, parentID string) error) *MockFileRepository_DeleteByParent_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) FindByID(ctx context.Context, id string) (*domain.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockFileRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFileRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockFileRepository_FindByID_Call {
	return &MockFileRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockFileRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockFileRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_FindByID_Call) Return(file *domain.File, err error) *MockFileRepository_FindByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.File, error)) *MockFileRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParent provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) FindByParent(ctx context.Context, parentTable string, parentID string, role domain.FileRole) ([]domain.File, error) {
	ret := _mock.Called(ctx, parentTable, parentID, role)

	if len(ret) == 0 {
		panic("no return value specified for FindByParent")
	}

	var r0 []domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.FileRole) ([]domain.File, error)); ok {
		return returnFunc(ctx, parentTable, parentID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.FileRole) []domain.File); ok {
		r0 = returnFunc(ctx, parentTable, parentID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.FileRole) error); ok {
		r1 = returnFunc(ctx, parentTable, parentID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_FindByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParent'
type MockFileRepository_FindByParent_Call struct {
	*mock.Call
}

// FindByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - parentTable string
//   - parentID string
//   - role domain.FileRole
func (_e *MockFileRepository_Expecter) FindByParent(ctx interface{}, parentTable interface{}, parentID interface{}, role interface{}) *MockFileRepository_FindByParent_Call {
	return &MockFileRepository_FindByParent_Call{Call: _e.mock.On("FindByParent", ctx, parentTable, parentID, role)}
}

func (_c *MockFileRepository_FindByParent_Call) Run(run func(ctx context.Context, parentTable string, parentID string, role domain.FileRole)) *MockFileRepository_FindByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.FileRole
		if args[3] != nil {
			arg3 = args[3].(domain.FileRole)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileRepository_FindByParent_Call) Return(files []domain.File, err error) *MockFileRepository_FindByParent_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_FindByParent_Call) RunAndReturn(run func(ctx context.Context, parentTable string, parentID string, role domain.FileRole) ([]domain.File, error)) *MockFileRepository_FindByParent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Update(ctx context.Context, fileUpdate domain.File) (*domain.File, error) {
	ret := _mock.Called(ctx, fileUpdate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) (*domain.File, error)); ok {
		return returnFunc(ctx, fileUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) *domain.File); ok {
		r0 = returnFunc(ctx, fileUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.File) error); ok {
		r1 = returnFunc(ctx, fileUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - fileUpdate domain.File
func (_e *MockFileRepository_Expecter) Update(ctx interface{}, fileUpdate interface{}) *MockFileRepository_Update_Call {
	return &MockFileRepository_Update_Call{Call: _e.mock.On("Update", ctx, fileUpdate)}
}

func (_c *MockFileRepository_Update_Call) Run(run func(ctx context.Context, fileUpdate domain.File)) *MockFileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.File
		if args[1] != nil {
			arg1 = args[1].(domain.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Update_Call) Return(file *domain.File, err error) *MockFileRepository_Update_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, fileUpdate domain.File) (*domain.File, error)) *MockFileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Upload(ctx context.Context, file *domain.FileUploadRequest) (*domain.FileUploaded, error) {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domain.FileUploaded
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FileUploadRequest) (*domain.FileUploaded, error)); ok {
		return returnFunc(ctx, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FileUploadRequest) *domain.FileUploaded); ok {
		r0 = returnFunc(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FileUploaded)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.FileUploadRequest) error); ok {
		r1 = returnFunc(ctx, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockFileRepository_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file *domain.FileUploadRequest
func (_e *MockFileRepository_Expecter) Upload(ctx interface{}, file interface{}) *MockFileRepository_Upload_Call {
	return &MockFileRepository_Upload_Call{Call: _e.mock.On("Upload", ctx, file)}
}

func (_c *MockFileRepository_Upload_Call) Run(run func(ctx context.Context, file *domain.FileUploadRequest)) *MockFileRepository_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FileUploadRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.FileUploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Upload_Call) Return(fileUploaded *domain.FileUploaded, err error) *MockFileRepository_Upload_Call {
	_c.Call.Return(fileUploaded, err)
	return _c
}

func (_c *MockFileRepository_Upload_Call) RunAndReturn(run func(ctx context.Context, file *domain.FileUploadRequest) (*domain.FileUploaded, error)) *MockFileRepository_Upload_Call {
	_c.Call.Return(run)
	return _c
}
