// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/fingertips18/fingertips18.github.io/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageRepository is an autogenerated mock type for the ImageRepository type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Upload(ctx context.Context, image *domain.ImageUploadRequest) (*domain.ImageUploadFile, error) {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domain.ImageUploadFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ImageUploadRequest) (*domain.ImageUploadFile, error)); ok {
		return returnFunc(ctx, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ImageUploadRequest) *domain.ImageUploadFile); ok {
		r0 = returnFunc(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ImageUploadFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ImageUploadRequest) error); ok {
		r1 = returnFunc(ctx, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageRepository_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - image *domain.ImageUploadRequest
func (_e *MockImageRepository_Expecter) Upload(ctx interface{}, image interface{}) *MockImageRepository_Upload_Call {
	return &MockImageRepository_Upload_Call{Call: _e.mock.On("Upload", ctx, image)}
}

func (_c *MockImageRepository_Upload_Call) Run(run func(ctx context.Context, image *domain.ImageUploadRequest)) *MockImageRepository_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ImageUploadRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.ImageUploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Upload_Call) Return(imageUploadFile *domain.ImageUploadFile, err error) *MockImageRepository_Upload_Call {
	_c.Call.Return(imageUploadFile, err)
	return _c
}

func (_c *MockImageRepository_Upload_Call) RunAndReturn(run func(ctx context.Context, image *domain.ImageUploadRequest) (*domain.ImageUploadFile, error)) *MockImageRepository_Upload_Call {
	_c.Call.Return(run)
	return _c
}
