name: Portfolio - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          npm run deploy
