name: Portfolio - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          name: dist-artifact
          github_token: ${{ github.token }}
          workflow: build.yaml
          workflow_search: true
          workflow_conclusion: success
          path: dist/

      - name: Setup Git Identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install gh-pages
        run: npm install gh-pages

      - name: Deploy to GitHub Pages
        run: npm run deploy
